baseURL = "http://paulcohn.net/"
languageCode = "en-us"
title = "Paul Cohn"
theme = "minimo"

[author.social]
  twitter = "paulsterr"
  github = "pscohn"

[[menu.main]]
  name = "Home"
  weight = 1
  url = "/"
